version: '3'

services:
    php-fpm:
        build:
            context: docker/php-fpm
        volumes:
            - ./src:/var/www
        networks:
            - local_network
        user: ${USER}

    nginx:
        build:
            context: docker/nginx
        volumes:
            - ./src:/var/www
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/sites/:/etc/nginx/sites-available
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d
        networks:
            - local_network
        links:
            - php-fpm
        ports:
            - "80:80"

    mariadb:
        image: mariadb:10.5.5
        environment:
            MYSQL_ROOT_PASSWORD: "rootpassword"
        networks:
            - local_network
        ports:
            - "3306:3306"

networks:
    local_network:
